version: "3.9"
services: 
  db:
    build: .
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_PASSWORD=godsounds
      - POSTGRES_USER=postgres
      - POSTGRES_DB=godsounds
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"

volumes:
  pg_data:
