version: "3.9"
services: 
  db:
    build: .
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"

volumes:
  pg_data:
